ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- 테이블 스페이스 생성
CREATE TABLESPACE myts DATAFILE 'E:\oradb\myts.dbf' SIZE 100M AUTOEXTEND ON NEXT 5M;
-- 스프링 부트 사용자 생성
CREATE USER kamp IDENTIFIED BY kamp
DEFAULT TABLESPACE myts;

-- 스프링 부트 사용자 계정에 권한 부여
GRANT CONNECT, RESOURCE TO kamp;
GRANT CREATE VIEW TO kamp;

--boot_user에 대한 테이블 스페이스 공간 할당
alter user kamp default tablespace myts quota unlimited on myts; 

--컬럼크기 늘리기 (6/12)
ALTER TABLE REVIEW ADD (CONTENT_TEMP CLOB);
UPDATE REVIEW SET CONTENT_TEMP = CONTENT;
ALTER TABLE REVIEW DROP COLUMN CONTENT;
ALTER TABLE REVIEW RENAME COLUMN CONTENT_TEMP TO CONTENT;

--제약조건추가 (6/12) 제약이없다고 나와도 ok 있으면 삭제
ALTER TABLE review DROP CONSTRAINT UK_FCXHKV3RF2KCUKXTMBXLNEWXJ;
ALTER TABLE notice DROP CONSTRAINT UKGW7MKX7AX3YE2IPTKP6AH0Y01;
ALTER TABLE book DROP CONSTRAINT UK6KCJRHL9YF3G278KP065FALX9;

